### ISSUE TITLE
absolute path support

### ISSUE THREAD

**Issue by Dimon70007** [shameemz/babel-plugin-variable-path-resolver#1]
How we are could use it for importing files with absolute path? For example, instead `import Foo from '../../../{Bar}/whatever';` write `import Foo from '{Bar}/whatever';`
I also tryed to import relative variable path to dir with package.json and export from it with name, specified in package.json and has got this error in runtime

> The development server returned response error code: 500
> URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false
> Body:
> {"type":"TransformError","lineNumber":0,"errors":[{"description":"/myProject/lib/Root.js: /myProject/lib/Root.js: ENOENT: no such file or directory, uv_cwd","lineNumber":0}],"name":"SyntaxError","message":"/myProject/lib/Root.js: /myProject/lib/Root.js: ENOENT: no such file or directory, uv_cwd","stack":"Error: /myProject/lib/Root.js: ENOENT: no such file or directory, uv_cwd\n    at normalizeCwd (/myProject/node_modules/babel-plugin-variable-path-resolver/lib/normalizeOptions.js:63:25)\n    at exports.default (/myProject/node_modules/babel-plugin-variable-path-resolver/lib/normalizeOptions.js:132:15)\n    at /myProject/node_modules/reselect/lib/index.js:76:25\n    at /myProject/node_modules/reselect/lib/index.js:36:25\n    at /myProject/node_modules/reselect/lib/index.js:90:33\n    at /myProject/node_modules/reselect/lib/index.js:36:25\n    at PluginPass.pre (/myProject/node_modules/babel-plugin-variable-path-resolver/lib/index.js:49:58)\n    at File.call (/myProject/node_modules/babel-core/lib/transformation/file/index.js:596:18)\n    at File.transform (/myProject/node_modules/babel-core/lib/transformation/file/index.js:512:12)"}
> processBundleResult
>     BundleDownloader.java:266
> access$200
>     BundleDownloader.java:35
> onResponse
>     BundleDownloader.java:153
> onResponse
>     null
> execute
>     RealCall.java:135
> run
>     NamedRunnable.java:32
> runWorker
>     ThreadPoolExecutor.java:1112
> run
>     ThreadPoolExecutor.java:587
> run
>     Thread.java:818

[info about absolute path](https://willowtreeapps.com/ideas/react-native-tips-and-tricks-2-0-managing-static-assets-with-absolute-paths/)

**Comment by Dimon70007** [comment]
with error it was my mistake - i'm trying to export default from index.js file where were used export.
after moving all to separate file with default export - i've done. and now i have an absolute export from @mymodule, that contains many different configs and imports they with `babel-plugin-variable-path-resolver` syntax.
